=== ferso1212/I-Pazzi/blue-deck-schema.dtd
<!ELEMENT SubDeckBlue (CharacterCard*)>
<!ELEMENT CharacterCard (Requirement*, Cost*, InstantEffect, PermanentEffect*)>
<!ELEMENT Requirement (Properties, CardsNumber)>
<!ELEMENT Cost (Properties)>

<!ELEMENT InstantEffect (EffectSet*)>

<!ELEMENT EffectSet (NullEffect?, PropEffect?, DiscountEffect?, CardDiceEffect?, BlockTowerEffect?, CouncilEffect?, MultiplierEffect?, PickAnotherCardEffect?, ExtraWorkEffect?)>

<!ELEMENT PropEffect (Requirement*, Properties)>
<!ELEMENT NullEffect EMPTY>
<!ELEMENT DiscountEffect (Requirement*,>

<!ELEMENT PickAnotherCard (DevelopmentCardType?, DevelopmentCardType?, DevelopmentCardType?, DevelopmentCardType?)>

<!ELEMENT Properties (Wood, Stones, Servants, Coins, MilitaryPoints, VictoryPoints, FaithPoints)>
<!ELEMENT Coins EMPTY>
<!ELEMENT Stones EMPTY>
<!ELEMENT Wood EMPTY>
<!ELEMENT Servants EMPTY>
<!ELEMENT MilitaryPoints EMPTY>
<!ELEMENT FaithPoints EMPTY>
<!ELEMENT VictoryPoints EMPTY>

<!ELEMENT CardsNumber (Green, Yellow, Blue, Purple)>
<!ELEMENT Green EMPTY>
<!ELEMENT Yellow EMPTY>
<!ELEMENT Blue EMPTY>
<!ELEMENT Purple EMPTY>

<!ELEMENT InstantEffect EMPTY>

<!ATTLIST Coins value CDATA #REQUIRED>
<!ATTLIST Stones value CDATA #REQUIRED>
<!ATTLIST Wood value CDATA #REQUIRED>
<!ATTLIST Servants value CDATA #REQUIRED>
<!ATTLIST MilitaryPoints value CDATA #REQUIRED>
<!ATTLIST FaithPoints value CDATA #REQUIRED>
<!ATTLIST VictoryPoints value CDATA #REQUIRED>

<!ATTLIST Green value CDATA #REQUIRED>
<!ATTLIST Yellow value CDATA #REQUIRED>
<!ATTLIST Blue value CDATA #REQUIRED>
<!ATTLIST Purple value CDATA #REQUIRED>
<!ATTLIST CharacterCard
	name CDATA #REQUIRED
	era CDATA #REQUIRED>

<!ATTLIST PickAnotherCard diceValue CDATA #REQUIRED>

=== ferso1212/I-Pazzi/blue-deck.xml
<?xml version="1.0" ?>
<!DOCTYPE SubDeckBlue SYSTEM "blue-deck-schema.dtd">
<SubDeckBlue>
    <CharacterCard name="name" era="1">
        <Requirement>
            <Properties>
                    <Wood value="0"/>
                    <Stones value="2"/>
                    <Servants value="3"/>
                    <Coins value="3"/>
                    <MilitaryPoints value="0"/>
                    <VictoryPoints value="1"/>
                    <FaithPoints value="2"/>
            </Properties>
	    <CardsNumber>
                <Green value="2"/>
		<Yellow value="0"/>                
		<Blue value="0"/>           
                <Purple value="0"/>
            </CardsNumber>
        </Requirement>
 	<Cost>
         <Properties>
                    <Wood value="0"/>
                    <Stones value="2"/>
                    <Servants value="3"/>
                    <Coins value="3"/>
                    <MilitaryPoints value="0"/>
                    <VictoryPoints value="1"/>
                    <FaithPoints value="2"/>
	</Properties>
         </Cost>
	<InstantEffect/>
    </CharacterCard>
</SubDeckBlue>
