=== ferso1212/I-Pazzi/green-deck-schema.dtd
<!ELEMENT SubDeckGreen (TerritoryCard*)>
<!ELEMENT TerritoryCard (Requirement*, Cost*, InstantEffect, PermanentEffect*)>
<!ELEMENT Requirement (Properties, CardsNumber)>
<!ELEMENT Cost (Properties)>
<!ELEMENT InstantEffect (EffectSet)>
<!ELEMENT EffectSet (NullEffect?, PropEffect?, DiscountEffect?, CardDiceEffect?, BlockTowerEffect?, CouncilEffect?, MultiplierEffect?, PickAnotherCardEffect?, ExtraWorkEffect?)>
<!ELEMENT PropEffect (Cost, Properties)>
<!ELEMENT NullEffect EMPTY>
<!ELEMENT DiscountEffect (Cost,Properties,Territory?, Building?, Character?, Venture?) >
<!ELEMENT BlockTowerEffect EMPTY>
<!ELEMENT CouncilEffect EMPTY>
<!ELEMENT MultiplierEffect EMPTY>
<!ELEMENT ExtraWorkEffect (Building?, Territory?)>
<!ELEMENT CardDiceEffect (Cost,Territory?, Building?) >
<!ELEMENT PickAnotherCard (DevelopmentCardType?, DevelopmentCardType?, DevelopmentCardType?, DevelopmentCardType?)>
<!ELEMENT Properties (Wood, Stones, Servants, Coins, MilitaryPoints, VictoryPoints, FaithPoints)>
<!ELEMENT Coins EMPTY>
<!ELEMENT Stones EMPTY>
<!ELEMENT Wood EMPTY>
<!ELEMENT Servants EMPTY>
<!ELEMENT MilitaryPoints EMPTY>
<!ELEMENT FaithPoints EMPTY>
<!ELEMENT VictoryPoints EMPTY>
<!ELEMENT CardsNumber (Green, Yellow, Blue, Purple)>
<!ELEMENT Green EMPTY>
<!ELEMENT Yellow EMPTY>
<!ELEMENT Blue EMPTY>
<!ELEMENT Purple EMPTY>


<!ATTLIST TerritoryCard name CDATA #REQUIRED
		period CDATA #REQUIRED
                diceRequirement CDATA #REQUIRED>

<!ATTLIST Coins value CDATA #REQUIRED>
<!ATTLIST Stones value CDATA #REQUIRED>
<!ATTLIST Wood value CDATA #REQUIRED>
<!ATTLIST Servants value CDATA #REQUIRED>
<!ATTLIST MilitaryPoints value CDATA #REQUIRED>
<!ATTLIST FaithPoints value CDATA #REQUIRED>
<!ATTLIST VictoryPoints value CDATA #REQUIRED>
<!ATTLIST Green value CDATA #REQUIRED>
<!ATTLIST Yellow value CDATA #REQUIRED>
<!ATTLIST Blue value CDATA #REQUIRED>
<!ATTLIST Purple value CDATA #REQUIRED>
<!ATTLIST PickAnotherCard diceValue CDATA #REQUIRED>
<!ATTLIST CardDiceEffect diceValue CDATA #REQUIRED>
<!ATTLIST CouncilEffect value CDATA #REQUIRED>
<!ATTLIST CouncilEffect value CDATA #REQUIRED
			factorType CDATA #REQUIRED>
<!ATTLIST ExtraWorkEffect diceValue CDATA #REQUIRED>

=== ferso1212/I-Pazzi/green-deck.xml
<?xml version="1.0" ?>
<!DOCTYPE SubDeckGreen SYSTEM "green-deck-schema.dtd">
<SubDeckGreen>
    <TerritoryCard name="Ducato" period="2" diceRequirement="6">
        <Requirement>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="0" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
            <CardsNumber>
                <Green value="0" />
                <Yellow value="0" />
                <Blue value="0" />
                <Purple value="0" />
            </CardsNumber>
        </Requirement>
        <Cost>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="0" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
        </Cost>
        <InstantEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="0" />
                        <Stones value="0" />
                        <Servants value="0" />
                        <Coins value="4" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="0" />
                        <FaithPoints value="3" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </InstantEffect>
        <PermanentEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="2" />
                        <Stones value="1" />
                        <Servants value="0" />
                        <Coins value="1" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="0" />
                        <FaithPoints value="0" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </PermanentEffect>
    </TerritoryCard>
    <TerritoryCard name="CittÃ  Mercantile" period="3" diceRequirement="1">
        <Requirement>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="0" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
            <CardsNumber>
                <Green value="0" />
                <Yellow value="0" />
                <Blue value="0" />
                <Purple value="0" />
            </CardsNumber>
        </Requirement>
        <Cost>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="0" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
        </Cost>
        <InstantEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="0" />
                        <Stones value="0" />
                        <Servants value="1" />
                        <Coins value="1" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="0" />
                        <FaithPoints value="0" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </InstantEffect>
        <PermanentEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="0" />
                        <Stones value="0" />
                        <Servants value="0" />
                        <Coins value="3" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="0" />
                        <FaithPoints value="0" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </PermanentEffect>
    </TerritoryCard>
        <TerritoryCard name="Provincia" period="3" diceRequirement="6">
        <Requirement>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="0" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
            <CardsNumber>
                <Green value="0" />
                <Yellow value="0" />
                <Blue value="0" />
                <Purple value="0" />
            </CardsNumber>
        </Requirement>
        <Cost>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="0" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
        </Cost>
        <InstantEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="0" />
                        <Stones value="0" />
                        <Servants value="0" />
                        <Coins value="0" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="0" />
                        <FaithPoints value="0" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </InstantEffect>
        <PermanentEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="0" />
                        <Stones value="0" />
                        <Servants value="0" />
                        <Coins value="0" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="0" />
                        <FaithPoints value="0" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </PermanentEffect>
    </TerritoryCard>
</SubDeckGreen>
