=== ferso1212/I-Pazzi/purple-deck-schema.dtd
<!ELEMENT SubDeckPurple (VentureCard*)>
<!ELEMENT VentureCard (RequirementAndCost*, InstantEffect, PermanentEffect*)>
<!ELEMENT RequirementAndCost (Requirement, Cost)>
<!ELEMENT Requirement (Properties, CardsNumber)>
<!ELEMENT Cost (Properties)>
<!ELEMENT InstantEffect (EffectSet)>
<!ELEMENT PermanentEffect (EffectSet)>
<!ELEMENT EffectSet (NullEffect?, PropEffect?, DiscountEffect?, CardDiceEffect?, BlockTowerEffect?, CouncilEffect?, MultiplierEffect?, PickAnotherCardEffect?, ExtraWorkEffect?, PrivilegeEffect?, WorkDiceEffect?)>
<!ELEMENT PropEffect (Cost, Properties)>
<!ELEMENT NullEffect EMPTY>
<!ELEMENT PrivilegeEffect EMPTY>
<!ELEMENT DiscountEffect (Properties,Green?, Yellow?, Blue?, Purple?) >
<!ELEMENT BlockTowerEffect EMPTY>
<!ELEMENT CouncilEffect EMPTY>
<!ELEMENT MultiplierEffect (Cost, Properties, MultiplierType)>
<!ELEMENT MultiplierType (Wood|Stone|Coins|Servant|VictoryPoints|MilitaryPoints|FaithPoints|Blue|Green|Purple|Yellow)>
<!ELEMENT ExtraWorkEffect (Harvest?, Production?)>
<!ELEMENT Harvest EMPTY>
<!ELEMENT Production EMPTY>
<!ATTLIST ExtraWorkEffect diceValue CDATA #REQUIRED>
<!ELEMENT CardDiceEffect (Green?, Yellow?, Blue?, Purple?) >
<!ELEMENT PickAnotherCardEffect (Green?, Yellow?, Blue?, Purple?)>
<!ELEMENT Properties (Wood, Stones, Servants, Coins, MilitaryPoints, VictoryPoints, FaithPoints)>
<!ELEMENT Coins EMPTY>
<!ELEMENT Stones EMPTY>
<!ELEMENT Wood EMPTY>
<!ELEMENT Servants EMPTY>
<!ELEMENT MilitaryPoints EMPTY>
<!ELEMENT FaithPoints EMPTY>
<!ELEMENT VictoryPoints EMPTY>
<!ELEMENT CardsNumber (Green, Yellow, Blue, Purple)>
<!ELEMENT Green EMPTY>
<!ELEMENT Yellow EMPTY>
<!ELEMENT Blue EMPTY>
<!ELEMENT Purple EMPTY>



<!ATTLIST VentureCard name CDATA #REQUIRED
		period CDATA #REQUIRED>
<!ATTLIST Coins value CDATA #REQUIRED>
<!ATTLIST Stones value CDATA #REQUIRED>
<!ATTLIST Wood value CDATA #REQUIRED>
<!ATTLIST Servants value CDATA #REQUIRED>
<!ATTLIST MilitaryPoints value CDATA #REQUIRED>
<!ATTLIST FaithPoints value CDATA #REQUIRED>
<!ATTLIST VictoryPoints value CDATA #REQUIRED>
<!ATTLIST Green value CDATA #REQUIRED>
<!ATTLIST Yellow value CDATA #REQUIRED>
<!ATTLIST Blue value CDATA #REQUIRED>
<!ATTLIST Purple value CDATA #REQUIRED>
<!ATTLIST PickAnotherCardEffect diceValue CDATA #REQUIRED>
<!ATTLIST CardDiceEffect diceValue CDATA #REQUIRED>
<!ATTLIST CouncilEffect value CDATA #REQUIRED>
<!ATTLIST CouncilEffect value CDATA #REQUIRED
			factorType CDATA #REQUIRED>
<!ATTLIST ExtraWorkEffect diceValue CDATA #REQUIRED>
<!ATTLIST PrivilegeEffect number CDATA #REQUIRED>

=== ferso1212/I-Pazzi/purple-deck.xml
<?xml version="1.0" ?>
<!DOCTYPE SubDeckPurple SYSTEM "purple-deck-schema.dtd">
<SubDeckPurple>
    <VentureCard name="Combattere le Eresie" period="1">
        <Requirement>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="5" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
            <CardsNumber>
                <Green value="0" />
                <Yellow value="0" />
                <Blue value="0" />
                <Purple value="0" />
            </CardsNumber>
        </Requirement>
        <Cost>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="3" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
        </Cost>
        <InstantEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="0" />
                        <Stones value="0" />
                        <Servants value="0" />
                        <Coins value="0" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="0" />
                        <FaithPoints value="2" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </InstantEffect>
        <PermanentEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="0" />
                        <Stones value="0" />
                        <Servants value="0" />
                        <Coins value="0" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="5" />
                        <FaithPoints value="0" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </PermanentEffect>
    </VentureCard>
    <VentureCard name="Scavare Canalizzazioni" period="2">
        <Requirement>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="0" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
            <CardsNumber>
                <Green value="0" />
                <Yellow value="0" />
                <Blue value="0" />
                <Purple value="0" />
            </CardsNumber>
        </Requirement>
        <Cost>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="2" />
                <Coins value="3" />
                <MilitaryPoints value="0" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
        </Cost>
        <InstantEffect>
            <EffectSet>
                <ExtraWorkAction diceValue="4">
                    <Harvest />
                </ExtraWorkAction>
            </EffectSet>
        </InstantEffect>
        <PermanentEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="0" />
                        <Stones value="0" />
                        <Servants value="0" />
                        <Coins value="0" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="5" />
                        <FaithPoints value="0" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </PermanentEffect>
    </VentureCard>
    <VentureCard name="Conquista Militare" period="3">
        <Requirement>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="12" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
            <CardsNumber>
                <Green value="0" />
                <Yellow value="0" />
                <Blue value="0" />
                <Purple value="0" />
            </CardsNumber>
        </Requirement>
        <Cost>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="6" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
        </Cost>
        <InstantEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="3" />
                        <Stones value="3" />
                        <Servants value="0" />
                        <Coins value="3" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="0" />
                        <FaithPoints value="0" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </InstantEffect>
        <PermanentEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
                            <VictoryPoints value="0" />
                            <FaithPoints value="0" />
                        </Properties>
                    </Cost>
                    <Properties>
                        <Wood value="0" />
                        <Stones value="0" />
                        <Servants value="0" />
                        <Coins value="0" />
                        <MilitaryPoints value="0" />
                        <VictoryPoints value="7" />
                        <FaithPoints value="0" />
                    </Properties>
                </PropEffect>
            </EffectSet>
        </PermanentEffect>
    </VentureCard>
    <VentureCard name="Sostegno al Cardinale" period="2">
        <Requirement>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="7" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
            <CardsNumber>
                <Green value="0" />
                <Yellow value="0" />
                <Blue value="0" />
                <Purple value="0" />
            </CardsNumber>
        </Requirement>
        <Cost>
            <Properties>
                <Wood value="0" />
                <Stones value="0" />
                <Servants value="0" />
                <Coins value="0" />
                <MilitaryPoints value="4" />
                <VictoryPoints value="0" />
                <FaithPoints value="0" />
            </Properties>
        </Cost>
        <InstantEffect>
            <EffectSet>
                <PropEffect>
                    <Cost>
                        <Properties>
                            <Wood value="0" />
                            <Stones value="0" />
                            <Servants value="0" />
                            <Coins value="0" />
                            <MilitaryPoints value="0" />
