=== ferso1212/I-Pazzi/src/configuration/board-schema.dtd
<!ELEMENT Board (Privileges, InitialProperties, SimpleTile, AdvancedTiles, CardBonuses, CardRequirement, MilitaryBonuses, FaithBonuses, MarketBonuses, MarketPrivileges, CouncilBonus, CouncilPrivileges, TowersBonuses, ExcommunicationRequirements)>
<!ELEMENT Privileges (Properties*)>
<!ELEMENT InitialProperties (Properties*)>
<!ELEMENT Properties (Wood, Stones, Servants, Coins, MilitaryPoints, VictoryPoints, FaithPoints)>
<!ELEMENT Coins EMPTY>
<!ELEMENT SimpleTile (PersonalBonusTile)>
<!ELEMENT AdvancedTiles (PersonalBonusTile*)>
<!ELEMENT PersonalBonusTile (HarvestBonus, ProductionBonus)>
<!ELEMENT HarvestBonus (Properties)>
<!ELEMENT ProductionBonus (Properties)>
<!ELEMENT Stones EMPTY>
<!ELEMENT Wood EMPTY>
<!ELEMENT Servants EMPTY>
<!ELEMENT MilitaryPoints EMPTY>
<!ELEMENT FaithPoints EMPTY>
<!ELEMENT MarketPrivileges EMPTY>
<!ELEMENT VictoryPoints EMPTY>
<!ELEMENT CardBonuses (TerritoryBonuses, BuildingBonuses, CharacterBonuses, VentureBonuses)>
<!ELEMENT CharacterBonuses EMPTY>
<!ELEMENT BuildingBonuses EMPTY>
<!ELEMENT VentureBonuses EMPTY>
<!ELEMENT TerritoryBonuses EMPTY>
<!ELEMENT TowersBonuses (TerritoryTower, BuildingTower, CharacterTower, VentureTower)>
<!ELEMENT ExcommunicationRequirements EMPTY>

<!ELEMENT CardRequirement (TerritoryRequirement, BuildingRequirement, CharacterRequirement, VentureRequirement)>
<!ELEMENT CharacterRequirement (Requirement, Requirement, Requirement, Requirement, Requirement, Requirement)>
<!ELEMENT TerritoryRequirement (Requirement, Requirement, Requirement, Requirement, Requirement, Requirement)>
<!ELEMENT BuildingRequirement (Requirement, Requirement, Requirement, Requirement, Requirement, Requirement)>
<!ELEMENT VentureRequirement (Requirement, Requirement, Requirement, Requirement, Requirement, Requirement)>

<!ELEMENT Requirement (Properties, CardsNumber)>

<!ELEMENT FaithBonuses EMPTY>
<!ELEMENT MilitaryBonuses EMPTY>
<!ELEMENT MarketBonuses (Properties, Properties, Properties, Properties)>
<!ELEMENT CouncilBonus (Properties)>
<!ELEMENT CouncilPrivileges EMPTY>
<!ELEMENT CardsNumber (Green, Yellow, Blue, Purple)>
<!ELEMENT Green EMPTY>
<!ELEMENT Yellow EMPTY>
<!ELEMENT Blue EMPTY>
<!ELEMENT Purple EMPTY>

<!ELEMENT TerritoryTower (Properties, Properties, Properties, Properties)>
<!ELEMENT CharacterTower (Properties, Properties, Properties, Properties)>
<!ELEMENT VentureTower (Properties, Properties, Properties, Properties)>
<!ELEMENT BuildingTower (Properties, Properties, Properties, Properties)>


<!ATTLIST Green value CDATA #REQUIRED>
<!ATTLIST Yellow value CDATA #REQUIRED>
<!ATTLIST Blue value CDATA #REQUIRED>
<!ATTLIST Purple value CDATA #REQUIRED>
<!ATTLIST Coins value CDATA #REQUIRED>
<!ATTLIST Stones value CDATA #REQUIRED>
<!ATTLIST Wood value CDATA #REQUIRED>
<!ATTLIST Servants value CDATA #REQUIRED>
<!ATTLIST MilitaryPoints value CDATA #REQUIRED>
<!ATTLIST FaithPoints value CDATA #REQUIRED>
<!ATTLIST VictoryPoints value CDATA #REQUIRED>
<!ATTLIST MilitaryBonuses first CDATA #REQUIRED
			second CDATA #REQUIRED>
<!ATTLIST FaithBonuses zero CDATA #REQUIRED first CDATA #REQUIRED second CDATA #REQUIRED third CDATA #REQUIRED
			fourth CDATA #REQUIRED fifth CDATA #REQUIRED sixth CDATA #REQUIRED
			seventh CDATA #REQUIRED eighth CDATA #REQUIRED nineth CDATA #REQUIRED
			tenth CDATA #REQUIRED eleventh CDATA #REQUIRED twelveth CDATA #REQUIRED
			thirteenth CDATA #REQUIRED fourteenth CDATA #REQUIRED fifteenth CDATA #REQUIRED>
<!ATTLIST CouncilPrivileges value CDATA #REQUIRED>
<!ATTLIST TerritoryBonuses value0 CDATA #REQUIRED value1 CDATA #REQUIRED value2 CDATA #REQUIRED value3 
			CDATA #REQUIRED value4 CDATA #REQUIRED value5 CDATA #REQUIRED value6 CDATA #REQUIRED>
<!ATTLIST BuildingBonuses value0 CDATA #REQUIRED value1 CDATA #REQUIRED value2 CDATA #REQUIRED value3 
			CDATA #REQUIRED value4 CDATA #REQUIRED value5 CDATA #REQUIRED value6 CDATA #REQUIRED>
<!ATTLIST CharacterBonuses value0 CDATA #REQUIRED value1 CDATA #REQUIRED value2 CDATA #REQUIRED value3 
			CDATA #REQUIRED value4 CDATA #REQUIRED value5 CDATA #REQUIRED value6 CDATA #REQUIRED>
<!ATTLIST VentureBonuses value0 CDATA #REQUIRED value1 CDATA #REQUIRED value2 CDATA #REQUIRED value3 
			CDATA #REQUIRED value4 CDATA #REQUIRED value5 CDATA #REQUIRED value6 CDATA #REQUIRED>
<!ATTLIST ExcommunicationRequirements firstPeriod CDATA #REQUIRED  secondPeriod CDATA #REQUIRED thirdPeriod CDATA #REQUIRED>
<!ATTLIST MarketPrivileges first CDATA #REQUIRED second CDATA #REQUIRED third CDATA #REQUIRED
			fourth CDATA #REQUIRED>
<!ATTLIST HarvestBonus diceReq CDATA #REQUIRED>
<!ATTLIST ProductionBonus diceReq CDATA #REQUIRED>
<!ATTLIST PersonalBonusTile id CDATA #REQUIRED>

=== ferso1212/I-Pazzi/board.xml
<?xml version="1.0" ?>
<!DOCTYPE Board SYSTEM "board-schema.dtd">
<Board>
  <Privileges>
	<Properties>
                    <Wood value="1"/>
                    <Stones value="1"/>
                    <Servants value="0"/>
                    <Coins value="0"/>
                    <MilitaryPoints value="0"/>
                    <VictoryPoints value="0"/>
                    <FaithPoints value="0"/>
        </Properties>
	<Properties>
                    <Wood value="0"/>
                    <Stones value="0"/>
                    <Servants value="2"/>
                    <Coins value="0"/>
                    <MilitaryPoints value="0"/>
                    <VictoryPoints value="0"/>
                    <FaithPoints value ="0"/>
        </Properties>
	<Properties>
                    <Wood value="0"/>
                    <Stones value="0"/>
                    <Servants value="0"/>
                    <Coins value="2"/>
                    <MilitaryPoints value="0"/>
                    <VictoryPoints value="0"/>
                    <FaithPoints value="0"/>
        </Properties>
	<Properties>
                    <Wood value="0"/>
                    <Stones value="0"/>
                    <Servants value="0"/>
                    <Coins value="0"/>
                    <MilitaryPoints value="2"/>
                    <VictoryPoints value="0"/>
                    <FaithPoints value ="0"/>
        </Properties>
	<Properties>
                    <Wood value="0"/>
                    <Stones value="0"/>
                    <Servants value="0"/>
                    <Coins value="0"/>
                    <MilitaryPoints value="0"/>
                    <VictoryPoints value="0"/>
                    <FaithPoints value="1"/>
        </Properties>
   </Privileges> 
   <InitialProperties>
	<Properties>
                    <Wood value="2"/>
                    <Stones value="2"/>
                    <Servants value="3"/>
                    <Coins value="5"/>
                    <MilitaryPoints value="0"/>
                    <VictoryPoints value="0"/>
                    <FaithPoints value ="0"/>
        </Properties>
	<Properties>
                    <Wood value="2"/>
                    <Stones value="2"/>
                    <Servants value="3"/>
                    <Coins value="6"/>
                    <MilitaryPoints value="0"/>
                    <VictoryPoints value="0"/>
                    <FaithPoints value ="0"/>
        </Properties>
	<Properties>
                    <Wood value="2"/>
                    <Stones value="2"/>
                    <Servants value="3"/>
                    <Coins value="7"/>
                    <MilitaryPoints value="0"/>
                    <VictoryPoints value="0"/>
                    <FaithPoints value ="0"/>
        </Properties>
	<Properties>
                    <Wood value="2"/>
                    <Stones value="2"/>
                    <Servants value="3"/>
                    <Coins value="8"/>
                    <MilitaryPoints value="2"/>
                    <VictoryPoints value="0"/>
                    <FaithPoints value ="0"/>
        </Properties>
  </InitialProperties>
	<CardBonuses>
		<TerritoryBonus>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
		</TerritoryBonus>
		<BuildingBonus>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
		</BuildingBonus>
		<CharacterBonus>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
                		    <VictoryPoints value="0"/>
              			      <FaithPoints value ="0"/>
        		</Properties>
		</CharacterBonus>
		<VentureBonus>
			<Properties>
                		    <Wood value="2"/>
                		    <Stones value="2"/>
               			     <Servants value="3"/>
               			     <Coins value="8"/>
                		    <MilitaryPoints value="2"/>
