=== ferso1212/I-Pazzi/configuration/excommunications-schema.dtd
<!ELEMENT ExcommunicationDeck (Excommunication*)>
<!ELEMENT Excommunication (ActionExcommunication | CardDiceExcommunication | DiceExcommunication | FinalVPointExcommunication | PropAdditionExcommunication | ServantsValueExcommunication | WorkExcommunication )>
<!ELEMENT  ActionExcommunication EMPTY>
<!ELEMENT  CardDiceExcommunication (Green | Blue | Yellow | Purple)>
<!ELEMENT  DiceExcommunication EMPTY>
<!ELEMENT  FinalVPointExcommunication EMPTY>
<!ELEMENT  PropAdditionExcommunication (Properties) >
<!ELEMENT  ServantsValueExcommunication EMPTY >
<!ELEMENT  WorkExcommunication (Harvest | Production)>
<!ELEMENT Harvest EMPTY>
<!ELEMENT Production EMPTY>
<!ELEMENT Green EMPTY>
<!ELEMENT Yellow EMPTY>
<!ELEMENT Blue EMPTY>
<!ELEMENT Purple EMPTY>
<!ELEMENT Properties (Wood, Stones, Servants, Coins, MilitaryPoints, VictoryPoints, FaithPoints)>
<!ELEMENT Coins EMPTY>
<!ELEMENT Stones EMPTY>
<!ELEMENT Wood EMPTY>
<!ELEMENT Servants EMPTY>
<!ELEMENT MilitaryPoints EMPTY>
<!ELEMENT FaithPoints EMPTY>
<!ELEMENT VictoryPoints EMPTY>
<!ELEMENT FinalVPointsExcommunications (Green | Blue | Purple)>
<!ELEMENT FinalVPointsExcommunication (Properties)>
<!ELEMENT NoFInalVPointsForEveryResource EMPTY>
<!ELEMENT NoFinalVPointsForBuindingsCost EMPTY>


<!ATTLIST Excommunication id CDATA #REQUIRED period CDATA #REQUIRED >
<!ATTLIST ActionExcommunication delayFirstAction CDATA #REQUIRED noMarketAction CDATA #REQUIRED>
<!ATTLIST CardDiceExcommunication diceValue CDATA #REQUIRED>
<!ATTLIST DiceExcommunication whiteValue CDATA #REQUIRED blackValue CDATA #REQUIRED orangeValue CDATA #REQUIRED>
<!ATTLIST ServantsValueExcommunication servantsValue CDATA #REQUIRED>
<!ATTLIST WorkExcommunication value CDATA #REQUIRED>
<!ATTLIST Green value CDATA #REQUIRED>
<!ATTLIST Yellow value CDATA #REQUIRED>
<!ATTLIST Blue value CDATA #REQUIRED>
<!ATTLIST Purple value CDATA #REQUIRED>
<!ATTLIST Coins value CDATA #REQUIRED>
<!ATTLIST Stones value CDATA #REQUIRED>
<!ATTLIST Wood value CDATA #REQUIRED>
<!ATTLIST Servants value CDATA #REQUIRED>
<!ATTLIST MilitaryPoints value CDATA #REQUIRED>
<!ATTLIST FaithPoints value CDATA #REQUIRED>
<!ATTLIST VictoryPoints value CDATA #REQUIRED>

=== ferso1212/I-Pazzi/configuration/excommunications.xml
<?xml version="1.0" ?>
<!DOCTYPE ExcommunicationDeck SYSTEM "excommunications-schema.dtd">
<ExcommunicationDeck>
    <Excommunication id="0" period="1">
		<PropAdditionExcommunication>
			<Properties>
		                    <Wood value="0"/>
		                    <Stones value="0"/>
		                    <Servants value="0"/>
		                    <Coins value="0"/>
		                    <MilitaryPoints value="1"/>
		                    <VictoryPoints value="0"/>
		                    <FaithPoints value ="0"/>
			</Properties>			
		</PropAdditionExcommunication>
	</Excommunication >
    <Excommunication id="1" period="1">
		<PropAdditionExcommunication>
			<Properties>
		                    <Wood value="0"/>
		                    <Stones value="0"/>
		                    <Servants value="0"/>
		                    <Coins value="1"/>
		                    <MilitaryPoints value="0"/>
		                    <VictoryPoints value="0"/>
		                    <FaithPoints value ="0"/>
			</Properties>			
		</PropAdditionExcommunication>
	</Excommunication >
    <Excommunication id="2" period="1">
		<PropAdditionExcommunication>
			<Properties>
		                    <Wood value="0"/>
		                    <Stones value="0"/>
		                    <Servants value="1"/>
		                    <Coins value="0"/>
		                    <MilitaryPoints value="0"/>
		                    <VictoryPoints value="0"/>
		                    <FaithPoints value ="0"/>
			</Properties>			
		</PropAdditionExcommunication>
	</Excommunication >
    <Excommunication id="3" period="1">
		<PropAdditionExcommunication>
			<Properties>
		                    <Wood value="1"/>
		                    <Stones value="1"/>
		                    <Servants value="0"/>
		                    <Coins value="0"/>
		                    <MilitaryPoints value="0"/>
		                    <VictoryPoints value="0"/>
		                    <FaithPoints value ="0"/>
			</Properties>			
		</PropAdditionExcommunication>
	</Excommunication >
    <Excommunication id="4" period="1">
        <WorkExcommunication value="3">
            <Harvest/>
        </WorkExcommunication>
	</Excommunication >
    <Excommunication id="5" period="1">
        <WorkExcommunication value="3">
            <Production/>
        </WorkExcommunication>
	</Excommunication >
     <Excommunication id="6" period="1">
        <DiceExcommunication whitwValue="1" blackValue="1" orangeValue="1"/>
	</Excommunication >
    <Excommunication id="7" period="2">
        <CardDiceExcommunication diceValue="4">
            <Green value="0"/>
        </CardDiceExcommunication>
	</Excommunication >
    <Excommunication id="8" period="2">
        <CardDiceExcommunication diceValue="4">
            <Yellow value="0"/>
        </CardDiceExcommunication>
	</Excommunication >
    <Excommunication id="9" period="2">
        <CardDiceExcommunication diceValue="4">
            <Blue value="0"/>
        </CardDiceExcommunication>
	</Excommunication >
    <Excommunication id="10" period="2">
        <CardDiceExcommunication diceValue="4">
            <Purple value="0"/>
        </CardDiceExcommunication>
	</Excommunication >
    <Excommunication id="11" period="2">
        <ActionExcommunication delayFirstAction="0" noMarketAction="1"/>
	</Excommunication >
    <Excommunication id="12" period="2">
        <ServantsValueExcommunication servantsValue="2"/>
	</Excommunication >
    <Excommunication id="13" period="2">
        <ActionExcommunication delayFirstAction="1" noMarketAction="0"/>
	</Excommunication >
    <Excommunication id="14" period="3">
        <FinalVPointsExcommunications>
            <Blue value="0"/>
        </FinalVPointsExcommunications>
	</Excommunication >
    <Excommunication id="15" period="3">
        <FinalVPointsExcommunications>
            <Purple value="0"/>
        </FinalVPointsExcommunications>
	</Excommunication >
    <Excommunication id="16" period="3">
        <FinalVPointsExcommunications>
            <Green value="0"/>
        </FinalVPointsExcommunications>
	</Excommunication >
    <Excommunication id="17" period="3">
        <FinalVPointsExcommunication>
            <Properties>
		                    <Wood value="0"/>
		                    <Stones value="0"/>
		                    <Servants value="0"/>
		                    <Coins value="0"/>
		                    <MilitaryPoints value="0"/>
		                    <VictoryPoints value="5"/>
		                    <FaithPoints value ="0"/>
			</Properties>	
        </FinalVPointsExcommunication>
	</Excommunication >
    <Excommunication id="18" period="3">
        <FinalVPointsExcommunication>
            <Properties>
		                    <Wood value="0"/>
		                    <Stones value="0"/>
		                    <Servants value="0"/>
		                    <Coins value="0"/>
		                    <MilitaryPoints value="1"/>
		                    <VictoryPoints value="0"/>
		                    <FaithPoints value ="0"/>
			</Properties>	
        </FinalVPointsExcommunication>
	</Excommunication >
    <Excommunication id="19" period="3">
        <NoFinalVPointsForBuindingsCost/>
	</Excommunication >
    <Excommunication id="20" period="3">
        <NoFInalVPointsForEveryResource/>
	</Excommunication >
  	
	
</ExcommunicationDeck>
