=== ferso1212/I-Pazzi/configuration/leader-deck-schema.dtd
<!ELEMENT LeaderDeck (LeaderCard*)>
<!ELEMENT LeaderCard (InstantLeaderEffect | PermanentLeaderEffect)>
<!ELEMENT Requirement (Properties, CardsNumber)>
<!ELEMENT PermanentLeaderEffect ( ChurchSupport | DoubleResources | LorenzoIlMangifico | NoMilitaryForTerritory | NoPayOccupiedTower | OccupiedSpace | NullLeaderEffect | FixedDiceValues | IncreaseDiceValues | DiscountLeaderEffect | MemberBonus ) >
<!ELEMENT InstantLeaderEffect ( CouncilBonus | PropertiesBonus | PrivilegesBonus | InstantWorkEffect | LeaderPickAnotherCard | NullLeaderEffect )>
<!ELEMENT NoMilitaryForTerritory ( Requirement* ) >
<!ELEMENT DevelopmentCardType (Building | Territory | Character | Venture )>
<!ELEMENT OccupiedSpace (Requirement*) >
<!ELEMENT NoPayOccupiedTower ( Requirement* )>
<!ELEMENT ChurchSupport ( Requirement* ) >
<!ELEMENT CouncilBonus ( Requirement* ) >
<!ELEMENT FixedDiceValues (Requirement*)>
<!ELEMENT IncreaseDiceValues (Requirement*)>
<!ELEMENT DoubleResources ( Requirement* )>
<!ELEMENT LorenzoIlMagnifico ( Requirement* )>
<!ELEMENT MemberBonus ( Requirement* ) >
<!ELEMENT PropertiesBonus (Requirement* , Properties)>
<!ELEMENT LeaderPickAnotherCard (Requirement*)>
<!ELEMENT InstantWorkEffect (Requirement*, WorkType) >
<!ELEMENT WorkType (Harvest|Production)>
<!ELEMENT PrivilegesBonus (Requirement*)>
<!ELEMENT DiscountLeaderEffect (Requirement*)>	


<!ELEMENT NullLeaderEffect EMPTY>

<!ELEMENT MemberColor ( Black | Orange | White | Neutral )>
<!ELEMENT Black EMPTY>
<!ELEMENT Orange EMPTY>
<!ELEMENT White EMPTY>
<!ELEMENT Neutral EMPTY>
<!ELEMENT Building EMPTY>
<!ELEMENT Territory EMPTY>
<!ELEMENT Character EMPTY>
<!ELEMENT Venture EMPTY>
<!ELEMENT Harvest EMPTY>
<!ELEMENT Production EMPTY>

<!ELEMENT Properties (Wood, Stones, Servants, Coins, MilitaryPoints, VictoryPoints, FaithPoints)>
<!ELEMENT Coins EMPTY>
<!ELEMENT Stones EMPTY>
<!ELEMENT Wood EMPTY>
<!ELEMENT Servants EMPTY>
<!ELEMENT MilitaryPoints EMPTY>
<!ELEMENT FaithPoints EMPTY>
<!ELEMENT VictoryPoints EMPTY>

<!ELEMENT CardsNumber (Green, Yellow, Blue, Purple)>
<!ELEMENT Green EMPTY>
<!ELEMENT Yellow EMPTY>
<!ELEMENT Blue EMPTY>
<!ELEMENT Purple EMPTY>


<!ATTLIST LeaderCard name CDATA #REQUIRED>
<!ATTLIST Coins value CDATA #REQUIRED>
<!ATTLIST Stones value CDATA #REQUIRED>
<!ATTLIST Wood value CDATA #REQUIRED>
<!ATTLIST Servants value CDATA #REQUIRED>
<!ATTLIST MilitaryPoints value CDATA #REQUIRED>
<!ATTLIST FaithPoints value CDATA #REQUIRED>
<!ATTLIST VictoryPoints value CDATA #REQUIRED>
<!ATTLIST Green value CDATA #REQUIRED>
<!ATTLIST Yellow value CDATA #REQUIRED>
<!ATTLIST Blue value CDATA #REQUIRED>
<!ATTLIST Purple value CDATA #REQUIRED>

<!ATTLIST PrivilegeEffect number CDATA #REQUIRED>
<!ATTLIST CouncilBonus number CDATA #REQUIRED>
<!ATTLIST MemberBonus value CDATA #REQUIRED>
<!ATTLIST InstantWorkEffect diceValue CDATA #REQUIRED>
<!ATTLIST FixedDiceValues whiteValue CDATA #REQUIRED orangeValue CDATA #REQUIRED blackValue CDATA #REQUIRED > 
<!ATTLIST IncreaseDiceValues whiteValue CDATA #REQUIRED orangeValue CDATA #REQUIRED blackValue CDATA #REQUIRED > 
<!ATTLIST PrivilegesBonus number CDATA #REQUIRED>

=== ferso1212/I-Pazzi/src/configuration/leader-deck.xml
<?xml version="1.0" ?>
<!DOCTYPE LeaderDeck SYSTEM "leader-deck-schema.dtd">
<LeaderDeck>
	<LeaderCard name="Francesco Sforza">
		<InstantLeaderEffect>
			<InstantWorkEffect diceValue="1">
			<Requirement>
        		        <Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="0" />
        		            <Yellow value="0" />
    		                <Blue value="0" />
    		                <Purple value="5" />
    		            </CardsNumber>
  		          </Requirement>
				<WorkType>
					<Harvest/>
				</WorkType>
			</InstantWorkEffect>
		</InstantLeaderEffect>
	</LeaderCard>
	<LeaderCard name="Lucrezia Borgia">
	<PermanentLeaderEffect>
			<IncreaseDiceValues whiteValue="2" blackValue="2" orangeValue="2">
			<Requirement>
        		        <Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="6" />
        		            <Yellow value="0" />
    		                <Blue value="0" />
    		                <Purple value="0" />
    		            </CardsNumber>
  		          </Requirement>
			<Requirement>
        		        <Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="0" />
        		            <Yellow value="6" />
    		                <Blue value="0" />
    		                <Purple value="0" />
    		            </CardsNumber>
  		          </Requirement>
			<Requirement>
        		        <Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="0" />
        		            <Yellow value="0" />
    		                <Blue value="6" />
    		                <Purple value="0" />
    		            </CardsNumber>
  		          </Requirement>
			<Requirement>
        		        <Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="0" />
        		            <Yellow value="0" />
    		                <Blue value="0" />
    		                <Purple value="6" />
    		            </CardsNumber>
  		          </Requirement>
			</IncreaseDiceValues>			
		</PermanentLeaderEffect>
	</LeaderCard>
	<LeaderCard name="Sisto IV">
	<PermanentLeaderEffect>
		<ChurchSupport>
		<Requirement>
        		        <Properties>
        		            <Wood value="6" />
        		            <Stones value="6" />
        		            <Servants value="6" />
        		            <Coins value="6" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="0" />
        		            <Yellow value="0" />
    		                <Blue value="0" />
    		                <Purple value="0" />
    		            </CardsNumber>
  		          </Requirement>		
		</ChurchSupport>
	</PermanentLeaderEffect>
	</LeaderCard>
	<LeaderCard name="Federico da Montefeltro">
	<InstantLeaderEffect>
		<LeaderPickAnotherCard>
			<Requirement>
        		        <Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="5" />
        		            <Yellow value="0" />
    		                <Blue value="0" />
    		                <Purple value="0" />
    		            </CardsNumber>
  		          </Requirement>
		</LeaderPickAnotherCard>
	</InstantLeaderEffect>
	</LeaderCard>
	<LeaderCard name="Bartolomeo Colleoni">
	<InstantLeaderEffect>
	<PropertiesBonus>
			<Requirement>
        		        <Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="4" />
        		            <Yellow value="0" />
    		                <Blue value="0" />
    		                <Purple value="2" />
    		            </CardsNumber>
  		          </Requirement>
			<Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="4" />
        		            <FaithPoints value="0" />
        		 </Properties>
		</PropertiesBonus>
	</InstantLeaderEffect>
	</LeaderCard>
	<LeaderCard name="Michelangelo Bonarroti">
	<InstantLeaderEffect>
	<PropertiesBonus>
			<Requirement>
        		        <Properties>
        		            <Wood value="0" />
        		            <Stones value="10" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="0" />
        		            <Yellow value="0" />
    		                <Blue value="0" />
    		                <Purple value="0" />
    		            </CardsNumber>
  		          </Requirement>
			<Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="3" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		 </Properties>
	</PropertiesBonus>
	</InstantLeaderEffect>
	</LeaderCard>
	<LeaderCard name="Cosime de' Medici">
	<InstantLeaderEffect>
	<PropertiesBonus>
			<Requirement>
        		        <Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="0" />
        		            <Yellow value="4" />
    		                <Blue value="2" />
    		                <Purple value="0" />
    		            </CardsNumber>
  		          </Requirement>
			<Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="3" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="1" />
        		            <FaithPoints value="0" />
        		 </Properties>
		</PropertiesBonus>
	</InstantLeaderEffect>
	</LeaderCard>
	<LeaderCard name="Sandro Botticelli">
	<InstantLeaderEffect>
	<PropertiesBonus>
			<Requirement>
        		        <Properties>
        		            <Wood value="10" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="0" />
        		            <VictoryPoints value="0" />
        		            <FaithPoints value="0" />
        		        </Properties>
        		        <CardsNumber>
        		            <Green value="0" />
        		            <Yellow value="0" />
    		                <Blue value="0" />
    		                <Purple value="0" />
    		            </CardsNumber>
  		          </Requirement>
			<Properties>
        		            <Wood value="0" />
        		            <Stones value="0" />
        		            <Servants value="0" />
        		            <Coins value="0" />
        		            <MilitaryPoints value="2" />
        		            <VictoryPoints value="1" />
